#!/bin/sh

# Find out the latest revision
REVISION="\"HEAD\""
if [ -d "../.svn" ]; then
  REVISION=\""r`svn info . | sed -n 's/Revision: //p'`"\"
elif [ -d "../.git" ]; then
  REVISION=\""r`git svn info . | sed -n 's/Revision: //p'`"\"
elif [ -f "Version.py" ]; then
  # File exists, let's not change the version
  exit
fi
echo "#!/usr/bin/env python" > Version.py
echo "# encoding: utf-8" >> Version.py
echo "\"\"\"This is generated by the makefile via the shell program \'version.sh\'\"\"\"" >> Version.py
echo "subversionRevisionString =$REVISION" >> Version.py