<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>xmds</string>
	</array>
	<key>firstLineMatch</key>
	<string>&lt;?(?i:xmds)</string>
	<key>foldingStartMarker</key>
	<string>(?x)
		(^\s*(&lt;[^!?%/](?!.+?(/&gt;|&lt;/.+?&gt;))|&lt;[!%]--(?!.+?--%?&gt;)|&lt;%[!]?(?!.+?%&gt;))
		|^(?![^{]*?//|[^{]*?/\*(?!.*?\*/.*?\{)).*?\{\s*($|//|/\*(?!.*?\*/.*\S))
		)</string>
	<key>foldingStopMarker</key>
	<string>^\s*(&lt;/[^&gt;]+&gt;|[/%]&gt;|--&gt;)\s*$|^\s*\}</string>
	<key>keyEquivalent</key>
	<string>^~X</string>
	<key>name</key>
	<string>XMDS</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>&lt;!\[CDATA\[</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.tag.xml.xmds</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.c++.embedded.xmds</string>
			<key>end</key>
			<string>]]&gt;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.c++</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(complex|fftw_complex)\b</string>
					<key>name</key>
					<string>storage.type.c++.xmds</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b((r|p)complex|real|imag|mod(2)?|arg|conj|c_(exp|log|sqrt))\b</string>
					<key>name</key>
					<string>support.function.xmds</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bi\b</string>
					<key>name</key>
					<string>constant.numeric.c++.xmds</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>text.xml</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.xml.xmds</string>
	<key>uuid</key>
	<string>C57D99F8-C368-461F-B510-9590A6F552CB</string>
</dict>
</plist>
