#!/bin/bash

# This installer (currently) works for Debian and Debian based distros such
# as Ubuntu, as well as Fedora and Red Hat. Other distros may or may not work.

# Look for apt-get or yum to decide whether we should use a deb or rpm
# type of installation. If more distro support is added later, a finer
# grained detection scheme will probably be necessary.

# If this entire script is run as root, all the files created under the user's home
# directory will be owned by root, which can cause permissioning and deletion
# problems. Only the copying of the binaries to locations outside the user's
# directories should be run as sudo, which is taken care of within this script.
 
if [ "$(whoami)" = "root" ]; then
  echo
  echo "It seems you are running this installer as root or with the \"sudo\" "
  echo "command. Unless you're sure you know what you're doing, please exit"
  echo "and re-run this installer as a normal user (i.e. without \"sudo\")."
  echo
  echo "Continue? (Y/N)"

  read reply
  if [ $reply = "N" -o $reply = "n" ]; then
    exit
  fi
fi

echo $reply

echo
echo
echo "*** XMDS2 installer v0.3 ***"
echo
echo "A standard install downloads the XMDS 2.1 version of the code. This"
echo "is the default."
echo
echo "A developer install will download the latest cutting-edge version of"
echo "the XMDS code, which may include bugs. To perform a developer install,"
echo "run the installer with the --develop option."
echo
echo "In both cases an SVN repository will be created locally, and you can update"
echo "to the latest version of the code at any time by running the command"
echo "  make update"
echo "in the XMDS 2.1 directory."
echo
echo

DEB_INSTALL=0
RPM_INSTALL=0
if [ `which apt-get | wc -l` -ne 0 ]; then
  echo; echo "apt-get found; assuming Debian packaging scheme"; echo
  DEB_INSTALL=1
elif [ `which yum | wc -l` -ne 0 ]; then
  echo; echo "yum found; assuming RPM packaging scheme"; echo
  RPM_INSTALL=1
else
  echo
  echo "ERROR!"
  echo "This installer only works on Debian, Debian-based distributions such"
  echo "as Ubuntu and Mint, Fedora and Red Hat. Since neither \"apt-get\" "
  echo "nor \"yum\" is available, installation can't proceed."
  echo
  echo "Aborting install."
  echo
  exit
fi

XMDS2_install_directory=$HOME"/XMDS_2.1"
NUM_CPUS=`cat /proc/cpuinfo | grep processor | wc -l`
DEVELOPER_INSTALL=0

parse_command_line_arguments() {
  for i in $@; do
    if [ $i = "--help" ] || [ $i = "-h" ]; then
      echo
      echo "This is the XMDS 2.1 installer."
      echo
      echo "Usage: ./install [options]"
      echo
      echo "Options and arguments:"
      echo "--help          : this help text"
      echo "--develop       : perform a developer install, downloading the absolute lastest version of the code"
      echo
      echo "If no options are given, a standard install will be performed."
      echo
      exit
    elif [ $i = "--develop" ]; then
      DEVELOPER_INSTALL=1
    else
      echo "Unknown option:" $i
    fi
  done
}

install_FFTW() {

  # If version 3.3 of FFTW is available in the repos, use the package manager.
  # If it isn't, install it locally from source under the user's home directory.
  # Comment this code out until a distro actually includes fftw 3.3 in their
  # repository so I can test it, and make sure it comes with both single and
  # double precision libraries, and uses all the compile flags like mpi and avx
  #if [ DEB_INSTALL -eq 1 ]; then
  #  if [ `apt-cache policy libfftw3-dev | grep -i Candidate | grep 3.3 | wc -l -gt 0` ]; then
  #    sudo apt-get -y install libfftw3-dev
  #    $FFTW_install_directory=""
  #    return
  #  fi
  #else
  #  # Not sure how to handle rpms yet
  #  # $FFTW_install_directory=""
  #fi   

  # FFTW 3.3 wasn't in the repos, so install manually from source
  current_directory=`pwd`

  FFTW_install_directory=$XMDS2_install_directory"/fftw-3.3"
  
  cd $XMDS2_install_directory
  echo; echo "Downloading FFTW 3.3 from www.fftw.org..."; echo
  wget http://www.fftw.org/fftw-3.3.tar.gz

  # Make sure the fftw 3.3 archive is present
  if [ ! -f fftw-3.3.tar.gz ]; then
    echo
    echo "ERROR: Couldn't obtain fftw-3.3.tar.gz from www.fftw.org."
    echo "Aborting install."
    exit
  fi

  # Unpack the FFTW 3.3 archive and install it in the user's home directory structure.
  # This avoids conflicting with any other version of FFTW that may have been
  # installed system-wide. Later we'll tell XMDS to use this specific version.  
  tar -xzf fftw-3.3.tar.gz
  rm fftw-3.3.tar.gz
  cd $FFTW_install_directory

  echo
  echo "Installing FFTW. This can take several minutes if you only have a single CPU."
  
  NO_COMPILER_SUPPORT_FOR_AVX=0  

  echo "  Configuring FFTW with single precision option..."
  if [ $RPM_INSTALL -eq 1 ]; then
    export CPPFLAGS=$CPPFLAGS" -I"$MPIHEADERDIR
    export LDFLAGS=$LDFLAGS" -L"$MPILIBDIR
  fi

  ./configure --disable-fortran --enable-mpi --enable-single --enable-sse2 --enable-avx --prefix=$FFTW_install_directory > installer.log
  if [ $? -ne 0 ]; then
    # Nonzero error code returned, so something went wrong
    echo "    Configuration failed. Retrying without assuming your compiler supports AVX..."
    ./configure --disable-fortran --enable-mpi --enable-single --enable-sse2 --prefix=$FFTW_install_directory > installer.log
    if [ $? -ne 0 ]; then
      # Still no success, so bail out
      echo "Configuration failed due to some unknown reason. Aborting install."
      echo "Check installer.log in "$FFTW_install_directory " for more information."
      echo
      exit
    else
      echo "    Configuration successful!"
      NO_COMPILER_SUPPORT_FOR_AVX=1
    fi
  fi

  rm -f installer.log > /dev/null

  echo "  Compiling FFTW with single precision option..."
  make -j $NUM_CPUS 1>/dev/null
  
  echo "  Copying single precision libraries..."
  make install > /dev/null

  # Note: if precision is not specified, FFTW will compile double-precision libs by default
  echo "  Configuring FFTW with double precision option..."
  if [ $NO_COMPILER_SUPPORT_FOR_AVX -eq 0 ]; then
    ./configure --disable-fortran --enable-mpi --enable-sse2 --prefix=$FFTW_install_directory 1>/dev/null
  else
    ./configure --disable-fortran --enable-mpi --enable-sse2 --enable-avx --prefix=$FFTW_install_directory 1>/dev/null
  fi

  echo "  Compiling FFTW with double precision option..."
  make -j $NUM_CPUS 1>/dev/null

  echo "  Copying double precision libraries..."
  make install > /dev/null

  cd $current_directory
  echo
  echo "FFTW installed!"
  echo
}

parse_command_line_arguments $@

if [ $DEVELOPER_INSTALL -eq 1 ]; then
  echo "Performing developer install..."
else
  echo "Performing standard install..."
fi
echo
echo
echo "By default XMDS will be installed in " $XMDS2_install_directory
echo "Press [ENTER] to accept this default, or enter a new path:"
read reply

if [ ! -z $reply ]; then
  XMDS2_install_directory=$reply
fi

# check if XMDS directory exists
if [ ! -d $XMDS2_install_directory ]; then
  mkdir $XMDS2_install_directory
fi

echo
echo "Installing required packages..."
echo

if [ $DEB_INSTALL -eq 1 ]; then
  # Begin Debian package install
  sudo apt-get -y install build-essential libopenmpi-dev openmpi-bin python-setuptools python-cheetah python-pyparsing python-lxml python-numpy python-mpmath libhdf5-serial-dev libgsl0-dev subversion python-sphinx wget

  # Find the optimum ATLAS version (i.e. CBLAS implementation) and install it
  # Older versions of Ubuntu offered pre-optimized packages for various architectures,
  # but newer versions don't, as most of the optimizations are now done at build time.
  if [ `cat /proc/cpuinfo | grep sse3 |wc -l` -gt 0 ]; then
    if [ `cat /proc/cpuinfo | grep "Core(TM) i7" | wc -l` -ne 0 ] && [ `apt-cache --names-only search libatlas-corei7sse3-dev | wc -l` -ne 0 ]; then
      sudo apt-get -y install libatlas-corei7sse3-dev
    elif [ `apt-cache --names-only search libatlas-amd64sse3-dev | wc -l` -ne 0 ]; then
      sudo apt-get -y install libatlas-amd64sse3-dev
    else
      sudo apt-get -y install libatlas-base-dev
    fi
  else
    sudo apt-get -y install libatlas-base-dev
  fi 
  # End Debian packages install
elif [ $RPM_INSTALL -eq 1 ]; then
  # Begin RPM packages install
  sudo yum -y install gcc gcc-c++ make automake subversion openmpi-devel python-setuptools python-cheetah pyparsing python-lxml numpy python-mpmath hdf5-devel gsl-devel python-sphinx wget
  if [ `cat /proc/cpuinfo | grep sse3 |wc -l` -gt 0 ]; then
    sudo yum -y install atlas-sse3-devel
  elif [ `cat /proc/cpuinfo | grep sse2 |wc -l` -gt 0 ]; then
    sudo yum -y install atlas-sse2-devel
  else
    sudo yum -y install atlas-devel
  fi
  # End RPM packages install
fi

# Some distros put MPI libraries and binaries in a location that
# isn't in the default search path, allowing multiple MPI versions
# to coexist. Since we need to know where they are in order to compile stuff,
# find where they are located. The scheme below is annoying and fragile.
# A better way of doing this would be good.

sudo updatedb
MPIHEADER=`locate "/usr*/mpi.h" | grep -v "src/linux-headers" | head --lines=1`
MPILIB=`locate "/usr*mpi_cxx.so" | head --lines=1`
MPIHEADERDIR=`dirname $MPIHEADER`
MPILIBDIR=`dirname $MPILIB`

# Install FFTW3.3 from package manager if available, otherwise build from source
install_FFTW

# Fetch the XMDS2 source files
echo
echo "Contacting sourceforge to checkout XMDS source code. Please wait..."
echo
if [ $DEVELOPER_INSTALL -eq 1 ]; then
  # Fetch the latest XMDS2 source code from sourceforge
  cd $XMDS2_install_directory
  svn checkout https://xmds.svn.sourceforge.net/svnroot/xmds/trunk/xpdeint .
else
  # Fetch a known good version of the XMDS2 source code from sourceforge
  cd $XMDS2_install_directory
  svn checkout -r 2524 https://xmds.svn.sourceforge.net/svnroot/xmds/trunk/xpdeint .
fi

# Compile the Cheetah templates into Python
echo
echo "Compiling Cheetah templates..."
echo
make

# Creates the xmds2 and xsil2graphics2 files in /usr/bin (or wherever), 
# and copy xmds2 python code into the python install path (typically 
# something like /usr/lib/python2.7/site-packages), and tells Python
# about the new package.
echo
echo "Installing XMDS..."
echo
sudo ./setup.py develop

# Tell XMDS to use the fftw libraries we installed under the user's
# home directory, rather than any system version.
echo
echo "Configuring XMDS..."
echo

# Some distros don't have mpic++ and mpirun in their default executable path, so add a
# static link to it if necessary. Need to do this before calling xmds2 --reconfigure
if [ `which mpic++ | wc -l` -eq 0 ]; then
  MPICPPPATH=`locate -b "\mpic++" | head --lines=1`
  echo; echo "Creating symbolic link to $MPICPPPATH"; echo
  sudo ln -s $MPICPPPATH /usr/bin/mpic++
fi

if [ `which mpirun | wc -l` -eq 0 ]; then
  MPIRUNPATH=`locate -b "\mpirun" | head --lines=1`
  echo; echo "Creating symbolic link to $MPIRUNPATH"; echo
  sudo ln -s $MPIRUNPATH /usr/bin/mpirun
fi

# Some distros don't have the MPI libs in their library path so tell XMDS where to find them
# Also tell XMDS where the version of FFTW we just installed is, if it wasn't installed
# via the package manager
# Again, comment this code out until I actually have a distro that has fftw 3.3 in its
# repository so I can test the code works
#if [ $FFTW_install_directory="" ]
#  # FFTW installed via package manager
#  xmds2 --reconfigure --lib-path $MPILIBDIR --include-path $MPIHEADERDIR
#else
#  # FFTW installed from source under the user's directory
#  xmds2 --reconfigure --lib-path $FFTW_install_directory"/lib" --include-path $FFTW_install_directory"/include" --lib-path $MPILIBDIR --include-path $MPIHEADERDIR
#fi

xmds2 --reconfigure --lib-path $FFTW_install_directory"/lib" --include-path $FFTW_install_directory"/include" --lib-path $MPILIBDIR --include-path $MPIHEADERDIR


# Build the HTML documentation
cd $XMDS2_install_directory"/admin/userdoc-source"
make html

echo
echo "If no errors are displayed above, XMDS 2.1 is installed!"
echo
echo "To see the HTML documentation, point your browser at" $XMDS2_install_directory"/documentation/index.html"
echo "or go to www.xmds.org"
echo
echo "Release notes and instructions can be found in" $XMDS2_install_directory
echo
echo "You can always update to the latest version of XMDS at any time by running \"make update\" "
echo "in the top level XMDS_2.1 directory."


